version: '3.10'
services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - ./bot.env
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    ports:
      - "8000:8000"
    restart: always
    working_dir: /app
